# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Portugues Brasil'), ('en', 'Inglês')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
